### ISSUE TITLE
2019Q4 - 2.3 Integrate and host TSCI into webcompat metrics dashboard

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#105]

**Comment by laghee** [comment]
If I've understood this objective (and not missed an email along the way), the object here is to host the information from [this page](https://wiki.mozilla.org/Compatibility/TSCI_Top_10) in the metrics dashboard. This is hosting up-to-the-minute data rather than over-time data like most of current dashboards, so we'll need to decide how best to display them. Possibly something similar to the `needstriage` setup?

Edited to remove silly question that made no sense. 😜

**Comment by laghee** [comment]
Also, I'm assuming that preserving the click-through function is vital. Let me know if I'm wrong there.

**Comment by miketaylr** [comment]
@laghee sorry for the delay and being super vague!

The rough idea is to essentially host the data found here: https://docs.google.com/spreadsheets/d/1G6j2zGGk8JYnF6boxwCdnrxp1dk45eUQYPVeks4RPfU/edit#gid=633060484 -- we're mostly interested in the graph. Probably being able to click through to the sheets and the queries is good too.

The lamest possible implementation is a an `<iframe>`, but we'll need some sort of dyanamic abilities to read the spreadsheet ID and it will change from time to time: https://github.com/mozilla/tsci/issues/115

I hope to have time this week or next to tackle that blocker bug.

**Comment by laghee** [comment]
@miketaylr Ahhhh, OK, that makes much more sense. I figured there was something I was missing (apparently, the actual graph and a crap-ton of data 😆).

So, depending on how ambitious we/I want to get here on the lame-->slightly less lame implementation scale, this could get pretty complicated. I've been poking through the repo and the spreadsheet trying to figure out everything that's going on behind the scenes with varying degrees of success.

Seems like @karlcow had a good suggestion, if I understood it correctly in Issue #115 (https://github.com/mozilla/tsci/issues/115#issuecomment-535765967), to store the weekly data rather than saving it directly to a sheet. Maybe he and I can have a discussion about that, and I'll check back in here.

**Comment by miketaylr** [comment]
> Seems like @karlcow had a good suggestion, if I understood it correctly in Issue #115 ([mozilla/tsci#115 (comment)](https://github.com/mozilla/tsci/issues/115#issuecomment-535765967)), to store the weekly data rather than saving it directly to a sheet. Maybe he and I can have a discussion about that, and I'll check back in here.

SGTM!

**Comment by laghee** [comment]
While @miketaylr seems to be close to potentially resolving the overload in mozilla/tsci#115 (https://github.com/mozilla/tsci/pull/120) 🎉 , I've been looking at two potential preliminary setups that could work:

1. As @miketaylr suggested, I could throw up an `<iframe>` template (hoping that doesn't make @magsout want to kill me 😱 😡).

2. [We could use the Google Sheets API to have the metrics server query the current summary sheet](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.values/get) directly and fetch the values from the `A` date column and the `Q` through `S` data columns. This would need either an API key or a service account setup for the metrics server and access to the current sheet ID since it looks like that will be dynamic for now. 🔑 

Eventually, it seems like moving the data dump to our existing database would be easier to manage and give us more options for querying the data going forward. Even adding 500 rows a week, we'd only run up to 20,000ish extra rows a year (our current paid limit is 10,000,000, and we're at about 20,000 with our counts now). 🔢 

We'll call that step 2, though, and maybe we can tackle it for next quarter. 📆

**Comment by miketaylr** [comment]
Update: I landed the automation bits in the TSCI repo. Hoping to get this on cron somewhere and have an API that will return the current ID so @laghee can get us an iframe. :) Then we can do the nicer thing.

**Comment by miketaylr** [comment]
Update: 

I've set up a (temporary?) API that we can use for the iframe here: https://tsci.webcompat.com/currentDoc.json

Working on the bits to get this running on cron (going to set it up to run daily for the weekend and see if it blows up). If that works, I think we're in business to get something going on the client side. Either way, that URI will be stable and we can assume it will return a JSON object that looks like so:

`{"currentDoc":"1TNyor5WJcqSWcEx6V4OlTGBGndDFeu822EkrClH_MP4"}`

That can be used to construct a google sheets URL:

`https://docs.google.com/spreadsheets/d/${json.currentDoc}/edit#gid=0`

**Comment by miketaylr** [comment]
(ok, so admittedly i hadn't tried this yet... it looks like we have to publish the document and that will generate an embed for us. i'll see if there's a way around this... 🤞 https://en.support.wordpress.com/google-docs/).

@laghee but we're still good to move forward with setting up an additional menu item on the frontend if that's still something you'd like to hack on. i guess worst, worst case scenario we don't iframe it and the new menu page is literally a hyperlink to a regular sheet (lol?).

edit: OK, this looks pretty simple: https://stackoverflow.com/a/38617031 i'll file a bug.

**Comment by laghee** [comment]
Don't you love it when the lame way is also a pain in the 🐴 (close enough)?

I'll work up a slot for this to land on the client.

**Comment by laghee** [comment]
Looks like @miketaylr finished his side of this: https://github.com/mozilla/tsci/pull/128

I now have a duct tape and paperclip draft of this working directly in metrics-client: https://github.com/webcompat/webcompat-metrics-client/issues/212#issuecomment-557805533, and in the week or so I'll see if I can hook it up for metrics-server to grab the ID and serve it to the client to construct the URL: https://github.com/webcompat/webcompat-metrics-server/issues/131 ...

**Comment by laghee** [comment]
Server side is all set as of PR #132 https://github.com/webcompat/webcompat-metrics-server/pull/132 -- endpoint here: https://webcompat-metrics.herokuapp.com/data/tsci-doc

Client side is still technically in progress (https://github.com/webcompat/webcompat-metrics-client/pull/219), but is missing only the tiny (crucial) bit of logic that pulls out the sheet ID from the JSON object. Pretty sure @magsout can help me figure out what I'm doing wrong, and I'll be able to get it functioning in the next few days.

**Comment by laghee** [comment]
This is now basically done, PR #219 (https://github.com/webcompat/webcompat-metrics-client/pull/219) is approved and just waiting on some kind of resolution for the weird `X-Frame-Options` error. Can be merged at will.

**Comment by laghee** [comment]
@miketaylr merged yesterday, so TSCI is now live on the dashboard (data still aggregating at this point, but everything working 🤞 so far). 

Edited to add link: https://webcompat-dashboard.herokuapp.com/tsci?

**Comment by miketaylr** [comment]
Yes! Thanks so much @laghee and @magsout for the support here.
