### ISSUE TITLE
2019Q4 - 3.4 Investigate dockerization of webcompat.com application

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#109]

**Comment by karlcow** [comment]
![4791-conteneur-appart](https://user-images.githubusercontent.com/505230/65962666-221b0680-e494-11e9-8780-130363316fb5.jpg)

**Comment by karlcow** [comment]
And here we start.
@miketaylr http://www.otsukare.info/2019/10/02/docker-some-notes

**Comment by karlcow** [comment]
Interesting take on the persistence of a sqlite db in between containers.
> Persist the SQLite database between containers
> 
> Instead of trying to keep the container around, a much cleaner solution is to arrange for the database (or other files you’d like to persist) to be stored in the host’s filesystem. You can do this by adding another volume mount with -v to the run command. Here’s the full command, which stores the database with the source code:
https://developers.redhat.com/blog/2019/09/12/develop-with-flask-and-python-3-in-a-container-on-red-hat-enterprise-linux/

**Comment by karlcow** [comment]
# HEROKU

The current webcompat metrics dashboard is being deployed through/on heroku.  One of the benefits of heroku deployment is people [getting PR individual URLs for testing](https://devcenter.heroku.com/articles/github-integration-review-apps). Kind of removing the need for a staging instance. Any PR is a staging instance.

This made me think that if we use docker only for deploying stuff, maybe we do not need docker and we could "just" shift to full heroku.  I'm not a big fan of these solutions, maybe because of the habits of owning your own stuff and avoiding to rely on too many services. 

Heroku has no file system. It means that we would need to change a couple of things.

1. static assets hosting
2. images hosting, see #108 (old and new) See also the [S3 integration in Heroku](https://devcenter.heroku.com/articles/s3-upload-python).
3. Sessions sqlite DB [moved to Postgres](https://devcenter.heroku.com/articles/sqlite3)
4. topsites DB move to Postgres
5. milestones.json which is created when the application starts as a caching mechanism. Maybe MongoDB solution.
6. [uwsgi](https://uwsgi-docs.readthedocs.io/en/latest/tutorials/heroku_python.html) seems usable on heroku. Or [switch to gunicorn](https://devcenter.heroku.com/articles/python-gunicorn).
7. Oh! and the domain name, but that seems easy to [add custom domain name to heroku instances](https://devcenter.heroku.com/articles/custom-domains).


[memcache and performances for Flask on heroku](https://devcenter.heroku.com/articles/flask-memcache). Also check the notion of [dyno for web concurrency with gunicorn](https://devcenter.heroku.com/articles/optimizing-dyno-usage) on heroku.

That would do it.

**Comment by karlcow** [comment]
# SHIV

Another proposal [for deploying a simple app is Shiv](https://www.mattlayman.com/blog/2019/python-alternative-docker/). As explained on [Shiv](https://shiv.readthedocs.io/en/latest/) website

> Shiv is a command line utility for building fully self contained Python zipapps as outlined in PEP 441 but with all their dependencies included! Shiv’s primary goal is making distributing Python applications fast & easy.

example of a deployment with a [django app](https://shiv.readthedocs.io/en/latest/django.html).

**Comment by karlcow** [comment]
# PIKU

[piku project](https://github.com/piku) The tiniest PaaS you've ever seen. Piku allows you to do git push deployments to your own servers.

[piku codebase](https://github.com/piku/piku)
> The tiniest Heroku/CloudFoundry-like PaaS you've ever seen.
> piku, inspired by dokku, allows you do git push deployments to your own servers.

This is very much in development right now.

**Comment by johngian** [comment]
Since we've already done the move for a lot of projects from bare-metal servers to containers here are a couple of thoughts:

# PaaS
* Heroku is amazing for teams without dedicated Ops/SRE people working dedicated to the projects. It's very high level but if you don't need to have a low level approach for performance/security/etc reasons its good enough. The other problem is that the pricing model tends to be on the cheap side for non-prod workloads but gets a little bit more expensive when you want to scale up.

* For a self-hosted solution, I've heard that dokku has a good track record for being rock solid. Also it follows the heroku paradigm on how to deploy services

* Despite the hype around Kubernetes, as long as there are no dedicated people working on that, I think its an overkill. That said if you can tap into an already maintained running cluster, it might be a good way forward. 

#  Migrating to docker
What I've found pretty useful in the past is

* Migrating to a 12-factor-like setup for the configuration.
* Understanding which part of your app can be stateless and where state lives
* Understanding the notion of a container as a software packaging method (with some isolation up to an extend)
* Splitting the various components (web workers, background tasks, db, cache, SSL termination, load balancing) to different containers/services.
* Docker hub is not the most stable registry out there. Maybe it worths the effort to investigate other options.
* Making sure that the envs (local dev-env, stage, prod) are as similar as possible.
* For python projects specifically
  * I think [whitenoise](http://whitenoise.evans.io/en/stable/) is great to decouple serving static files from the actual frontend servers
  * The idea is that your app serves the files for you but it comes built-in with CDN, caching, compression features.

# Current docker setup
For various reasons I've already dockerized webcompat.com for my dev env and for debugging staging wsgi. This might be useful for future reference:
* Quick setup of wsgi+nginx to reproduce an issue from stage
  * https://github.com/johngian/webcompat.com/tree/docker-compose
* Regular dev env to run flask in a container
  * https://github.com/johngian/webcompat.com/commit/05e762e43fbaf6ccca2938bba0a46a938f1b381a

I hope this is helpful for your migration to the :cloud: :computer: :package: :cloud:

**Comment by karlcow** [comment]
Thanks a lot @johngian for the information. Super useful.
Could you review if you have time[ some of these notes about docker](http://www.otsukare.info/2019/10/02/docker-some-notes).

As for PaaS, we are using heroku already for http://webcompat-dashboard.herokuapp.com/ 
https://github.com/webcompat/webcompat-metrics-server/
https://github.com/webcompat/webcompat-metrics-client/

**Comment by karlcow** [comment]
Also for people reading along and not familiar with [12 factor app](https://12factor.net/)

**Comment by karlcow** [comment]
# 2019-10-29 
The more I look at it the more i wonder if it's necessary. In terms of cost/benefits. And Probably a PaaS if we want to virtualize a bit more would bring us "benefits with a loss of controls". Doing like webcompat dashboard and pushing to Heroku.

**Comment by johngian** [comment]
> Thanks a lot @johngian for the information. Super useful.
> Could you review if you have time[ some of these notes about docker](http://www.otsukare.info/2019/10/02/docker-some-notes).
> 
> As for PaaS, we are using heroku already for http://webcompat-dashboard.herokuapp.com/
> https://github.com/webcompat/webcompat-metrics-server/
> https://github.com/webcompat/webcompat-metrics-client/

Nice post @karlcow. Some comments about it:

* Dev setup + process can be significantly better if you build around it. In the end docker is "just resource isolation" in Linux kernel. It wont work out for you if you just take your stack and run it in containers.
* Container benefits not captured (i think): If built properly, you can have significantly less attack vectors (especially in a PaaS world), maintenance overhead and dependency management issues. Also from my experience, having environments so similar to each other (local, dev, stage, prod) it brings much more confidence to release code and can make prod issues debugging much easier

Other than that yeah, there is a lot of hype out there on why all software needs to be containerized which of course doesn't necessarily apply to all the cases.

**Comment by karlcow** [comment]
Yet [another example for dockerizing flask](https://testdriven.io/blog/dockerizing-flask-with-postgres-gunicorn-and-nginx/)

**Comment by karlcow** [comment]
docker is not necessary the answer. Once the images are separated for processing we have a lot more freedom, and we can imagine hosting the application on Heroku for example. The rest of the dockerization seems not necessary useful. But we could still do docker. The blocker is really the independance of the images.

**Comment by miketaylr** [comment]
@karlcow can we write up a summary comment and call this one done?

**Comment by karlcow** [comment]
So to be able to go to a docker or a Heroku solution, these are the friction points we need to address:

1. Move from sqllite to a postgres like solution for all our dbs, because basically you do not want to lose these data in between each deployment. 
  * session.db
  * topsites.db
2. Remove the dependency on start up for milestones.json
3. Rewrite the request/saving of assets (images and json) to a storage server (AWS S3 or other)
4. Move all the static assets to a storage server (css, js, images) to make the caching more effective. Heroku filesystem is ephemeral.

It's not a light modification. A probably a couple of quarters with the externalization of systems step by step. 

There is also probably a bit of documentation rewriting when we move to these solutions. 

A docker solution would need to address the same issues basically. Coming up with a dev image as @johngian did is simple enough for testing scenario, but not for prod as-is without moving the things outside of the image.

* Digital Ocean proposes to host docker images. 
* Heroku we have an account, we already use for the webcompat dashboards.

**Comment by karlcow** [comment]
[Deploying with Docker](https://devcenter.heroku.com/categories/deploying-with-docker)
