### ISSUE TITLE
2020Q2 - 1.6 Hunt from Home Support

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#129]
There will be some minimal engineering supported needed (likely just adding some strings to `EXTRA_LABELS`: https://github.com/webcompat/webcompat.com/blob/476c9c7e200c2eabb8a3d2d1ca3248606c3c2ebf/config/__init__.py#L211

The rest however, will be moderation + triage + diagnosis. We'll have more details in the coming days / weeks.

**Comment by miketaylr** [comment]
We're also gonna gather some GPU info for webrender bugs https://bugzilla.mozilla.org/show_bug.cgi?id=1627738 (@wisniewskit has already authored the patch).

And we need to update the privacy policy: https://github.com/webcompat/webcompat.com/issues/3282

**Comment by miketaylr** [comment]
Update: waiting to launch.

**Comment by Darkspirit** [comment]
https://community.mozilla.org/campaigns/hunt-from-home-phase-2/
> Search for the preference: gfx.webrender.all
> Set that to false and restart your browser – that will disable WebRender

Disabling the force-enable pref won't disable WebRender when it's enabled by default for a qualified device. Please change it to:
> Search for the preference: **gfx.webrender.force-disabled**
> Set that to **true** and restart your browser – that will disable WebRender

I report this bug here because haven't found this page on GitHub: https://github.com/search?q=%22Set+that+to+false+and+restart+your+browser%22
The [repo](https://github.com/mozilla/community-portal) linked in the footer does [not](https://github.com/mozilla/community-portal/search?q=Search+for+the+preference&unscoped_q=Search+for+the+preference) seem to contain this page.

**Comment by miketaylr** [comment]
@Darkspirit sorry, I just saw this -- Unfortunately we don't have access to the copy at https://community.mozilla.org/campaigns/hunt-from-home-phase-2/. Someone from the participation team controls that.

Update: I think we can call this one "done", in terms of engineering + triage support.

**Comment by miketaylr** [comment]
I'm grading this one a bit harshly, mostly because my take on the campaign is that it largely failed. Maybe 0.7 is a better score, but I don't think it matters much.
