### ISSUE TITLE
2020Q2 - 2.3 AC Report Site Issue improvements

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#132]
Partially carry-over work from https://github.com/mozilla/webcompat-team-okrs/issues/110, we want to actually land the port and flesh out the missing features (console logging, for example).

**Comment by denschub** [comment]
During my earlier development, I shimmed two APIs, which is now biting me. One is hiding the action on incompatible sites, but that can be easily worked around by simply not submitting a report when we deem the site unworthy. The reporter menu item is already constantly visible in Fenix, so that wouldn't be a change.

The trickier one, though, is i18n. At the moment, I shimmed that by simply using a static string every time, but that's not really shippable, as Fenix itself is localized, and it would be a bad move to ship a component that's not localizable. Localizing strings itself isn't hard in android-components land, but the tricky question is how we can get that into the WebExtension. I already pinged Tom, and hoping to have a brainstorming session soon.

**Comment by denschub** [comment]
The i18n API was fixed, but then we figured out that was not the best idea, as we can't import the translations into the A-C code. But that makes all APIs complete. I had to work on other things just to distance my brain a bit, but I continued yesterday by starting to write some notes about the patches I made and plan to land this week. :)

**Comment by denschub** [comment]
So, [here is the PR for android-components](https://github.com/mozilla-mobile/android-components/pull/7106), and I have a patch for Fenix ready that can land once the a-c PR is settled. For some reason, the `captureTab` API stopped working, even though it absolutely did work in my previous tests. I tried looking into that, but because I'm already way too late here, I decided to remove the screenshots for now and build a PR without them. 

I'm currently writing up some of the differences between the desktop and mobile versions, as well as a list of things that are missing. I'm also waiting on feedback from Fenix people about the APIs that should be supported, which allows us to make more plans on adding the other report details.

**Comment by denschub** [comment]
Fenix PR is merged as https://github.com/mozilla-mobile/fenix/pull/11241 (Emily had to import my patch so CI is happy).

Future follow-up improvements are/will be noted and tracked as dependencies of https://bugzilla.mozilla.org/show_bug.cgi?id=1643132.
