### ISSUE TITLE
2020Q3 - 1.3 Form v2 measurement and experiments

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#141]
The idea here is to try to understand how to improve the form v2 reporting experience. How do we get more reports, or how do we get more valid reports? Are there simple experiments we can run?

Some ideas here: https://docs.google.com/document/d/1SJgjLij3CPWDv0GjEGDwe7FfBhCaCOtBi83asRG8kSo/edit#

**Comment by miketaylr** [comment]
IMHO, when we pick this up, we should set a concrete, measurable goal, i.e., improve valid ratio by 10%.

**Comment by miketaylr** [comment]
@rosanardila can you link us to existing research please?

**Comment by miketaylr** [comment]
> @rosanardila can you link us to existing research please?

Here's the folder -- there's some good stuff in there worth considering as experimental directions: https://drive.google.com/drive/folders/1QXkAoVlHKF23SW85zCc9xt_-jeyOx61l

**Comment by ksy36** [comment]
Created a project https://github.com/webcompat/webcompat.com/projects/13

**Comment by ksy36** [comment]
Update: added analytics for see the rate of drop off on each step.

**Comment by miketaylr** [comment]
@ksy36 I forgot to deploy https://github.com/webcompat/webcompat.com/pull/3428 to production until just now. Sorry!

So, for measuring and comparing, Aug 6th 11:57ish UTC time is when that change went live.

**Comment by ksy36** [comment]
After deploying https://github.com/webcompat/webcompat.com/pull/3428 drop off rate at the description step went down.

From Jule 17th-August 5th drop off was 27.7%, and after the change was deployed (August 7th-August 17th) drop off is 6.19%. So about 20% more users moved to the next step, instead of leaving the site. That does not necessarily mean we get more valid reports, though :) Seems that there is not enough data on how many valid reports we got just yet, so have to wait on that. 

Will work on url step improvements next, since it has a high rate of drop offs as well

**Comment by ksy36** [comment]
Another set of changes was deployed on production today, August 24: https://github.com/webcompat/webcompat.com/issues/3429 , https://github.com/webcompat/webcompat.com/issues/3458

**Comment by ksy36** [comment]
Since deploy on Aug 6th the percent of valid reports remained more or less the same.
Since deploy on August 24 we got more reports (about a 100 more). Still have to wait to know on the number of valid reports since the last deploy.

**Comment by miketaylr** [comment]
Update: after looking at numbers, the valid % hasn't changed since the last deploy. Currently working on mobile perf, on a theory that it sucks so people report fewer bugs.

**Comment by ksy36** [comment]
Update: Mobile performance improvements are done, need to deploy the changes.  As for the numbers, in the past two weeks (week of Sept 7, Sept 14) the ratio of valid reports slightly went down. Not sure if that caused by the recent changes to the form, or something else, need to watch the numbers for the week of Sept 21.
