### ISSUE TITLE
2020Q4 - Create tool to migrate Bugzilla issues to web-bugs repo

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#142]
We have a goal to move all diagnosis to GitHub. In order to make the transition less painful, it would be nice to have a tool (commandline? web extension?) to do some (if not all) of the following: 

* take an existing Bugzilla issue, copy relevant information, 
* create a new web-bugs issue
* close the existing Bugzilla issue as MOVED and set See-Also bug to new web-bugs bug

**Comment by denschub** [comment]
(For the record, as discussed on Matrix)

I'm very much in favor of this idea, but I'm  against shipping this in our system addon, and I would hard-block that attempt:

Our site intervention addon is meant for shipping interventions when things break. There is a slight performance cost for each intervention, and even though the total cost is minimal, there is no reason to use it for unrelated things.

Adding custom functionality into Bugzilla and forcing that functionality to all users without the ability to turn it off will make people hate us. Justifiably so. There is a bit of mutual trust that people have to allow us ship an addon that does magic with people's websites, and iId rather not use that trust for things that are not website hotfixes. Adding stuff to Bugzilla also has the chance of breaking Bugzilla, or at least making UX worse for some people - and I'd rather not spin a system addon rollout just to fix that.

There is nothing special about our addon besides some pieces of native functionality. It's just content scripts at the end of the day, and such a "move from bugzilla to webcompat.com" addon does not require any of the native functionality. It also does not system addon privileges.

I like the idea of having such a feature, but I very strongly suggest making that it's own addon. Building that into its own WebExtension has pretty much no overhead besides a `manifest.json`. It could be uploaded to AMO, people can opt-into that, the addon can be updated via AMO without involving 10 people inside the company, ... :)

(Also, don't use a `@mozilla.com` or `@mozilla.org` extension ID for AMO - because it will be flagged for manual review, and it will be rejected. using `@ksenia-is-awesome.org` or `@webcompat.com` is fine, and it's what Mozillians generally do for addons like [phab-test-policy](https://addons.mozilla.org/en-US/firefox/addon/phab-test-policy/) or [Tom's testcase reducer](https://addons.mozilla.org/en-US/firefox/addon/testcase-reducer/) :))

**Comment by ksy36** [comment]
Update: created a repo https://github.com/webcompat/bugzilla-to-webcompat/ and working on the first issue

**Comment by ksy36** [comment]
Update: created an addon, added "Move to wepcompat' button and validation for required bug fields. Will be working on POSTing bug data to webcompat.com next

**Comment by ksy36** [comment]
This is complete, published the addon on AMO https://addons.mozilla.org/en-CA/firefox/addon/bugzilla-to-webcompat/
