### ISSUE TITLE
2020Q4 - Get Fenix Report Site Issue menu item to root level 

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#150]
https://bugzilla.mozilla.org/show_bug.cgi?id=1643144

**Comment by denschub** [comment]
I've had some chats, and am working on a patch, no real ETA yet, but this is "in progress".

**Comment by denschub** [comment]
This is probably at risk because I am facing some issues, as well as other issues taking more time than expected. That's probably fine, because this was part of the Q4 reserve anyway, but it's still in progress. :)

**Comment by denschub** [comment]
Someone in the android-components team now wants to work on that - so I'm doing some coordination to make that happen.

**Comment by denschub** [comment]
This work is delegated and most of the communication happened without me, so that's great. :mcarare is doing the relevant work. Here are the two issues where some discussion happened and where progress will be tracked:

* https://github.com/mozilla-mobile/fenix/issues/11631
* https://github.com/mozilla-mobile/android-components/issues/8593

**Comment by denschub** [comment]
This is the current Fenix Nightly:

<img width="264" alt="Screenshot 2020-10-23 at 17 20 40" src="https://user-images.githubusercontent.com/344777/97022315-42f94280-1554-11eb-89e1-4619bbdc75f0.png">

So I'll mark this as done. :)
