### ISSUE TITLE
2020Q3 - 1.4 Create outreach template tooling

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#158]
See https://docs.google.com/document/d/15pLZBwqQ85dKOelsUszsgk7gVyqV1AljHNIytklIgzU/edit with ideas.

@ksy36 can you link relevant bugs once they exist?

**Comment by ksy36** [comment]
Created a project https://github.com/webcompat/webcompat.com/projects/11

**Comment by ksy36** [comment]
Set up build and deployment, deployed first issue on https://webcompat-outreach.herokuapp.com/

**Comment by ksy36** [comment]
Update: This is almost done (need someone to review the code https://github.com/webcompat/outreach/pull/6)

**Comment by magsout** [comment]
@ksy36 I will 👍

**Comment by ksy36** [comment]
Update: Added an ability to generate a template by id, e.g. https://webcompat-outreach.herokuapp.com/issue/33213

Next step will be to add a comment with a link to the outreach template on the webcompat.com side once an issue is moved to `needscontact` or `contactready` (https://github.com/webcompat/webcompat.com/issues/3374)

**Comment by karlcow** [comment]
@ksy36 Maybe we can create a new route here. something along `https://webcompat.com/outreach/33213` with either a redirection, aka `Location` or a [`Content-Location`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Location) HTTP header. In case the ` webcompat-outreach.herokuapp.com` domain is sunset or modified one day, it gives more flexibility on our side to control the redirections, instead of having users ending up with a legacy redirection going to a `4**` code.

**Comment by ksy36** [comment]
Update: Now when the issue is moved to needscontact the comment with outreach link is added. Tested this on staging, will deploy to production once I figure out how to deal with a weird error I'm receiving with deployment script :/
