### ISSUE TITLE
2020Q4 - Regular System Addons Release rotations

### ISSUE THREAD

**Issue by karlcow** [mozilla/webcompat-team-okrs#164]
https://wiki.mozilla.org/Compatibility/Interventions_Releases#Intervention_Release_Owner_Schedule

We should aim to manually test interventions after a new release, so we can file bugs for removing against tracking issues. 

* Firefox 83 ([v16](https://bugzilla.mozilla.org/show_bug.cgi?id=1663967)) - Dennis - Landing target: **2020-10-08**
* Firefox 84 ([v17](https://bugzilla.mozilla.org/show_bug.cgi?id=1663978)) - Karl - Landing target: **2020-11-05**
* Firefox 85 ([v18](https://bugzilla.mozilla.org/show_bug.cgi?id=1663980)) - Ksenia - Landing target: **2020-12-03**

**Comment by softvision-oana-arbuzov** [comment]
**[Done]** 1st run - QA Verification progress available here: https://docs.google.com/spreadsheets/d/1F9vcSpLQ_hNBeZinsytGXlfXpJLW6vh7C0BJYtd9hIY/edit?pli=1#gid=1337514988

Interventions to be removed: 
https://bugzilla.mozilla.org/show_bug.cgi?id=1668463 Remove Intervention for dns.google.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1668465 Remove Intervention for reallygoodemails.com

**Comment by denschub** [comment]
v16 is currently landing with a green test run on autoland, so I'm confident it'll stick. However, we had to back out the console logging notifications temporarily, until issues with a test for the extension permission manager are resolved. There is chance I'll have to ship a v16.1 because of that, follow [bug 1670241](https://bugzilla.mozilla.org/show_bug.cgi?id=1670241) for updates.

Since @karlcow is up for the next rotation: It's fine to simply go ahead with v17 as if nothing out of the ordinary happened. If I end up shipping a v16.1, I'll coordinate with you to avoid conflicts. Also, the current `master` branch of the system addon does **not** contain the test-failing code, so you can work and export as usual without any concerns.

**Comment by softvision-oana-arbuzov** [comment]
QA verification 2nd run will be done on 29th October, 2020.

**Comment by softvision-oana-arbuzov** [comment]
[Done] 2nd run - QA Verification progress available here: https://docs.google.com/spreadsheets/d/1F9vcSpLQ_hNBeZinsytGXlfXpJLW6vh7C0BJYtd9hIY/edit?pli=1#gid=471797029

Interventions to be removed:
https://bugzilla.mozilla.org/show_bug.cgi?id=1674098 Remove intervention for www.kitkat.com.au

**Comment by karlcow** [comment]
[v17.0.0 has been released.  ](https://bugzilla.mozilla.org/show_bug.cgi?id=1663978)
Thanks @denschub for holding my hands for some of the steps.

**Comment by karlcow** [comment]
@ksy36 is the next in line.

**Comment by softvision-oana-arbuzov** [comment]
QA verification 3rd run will be done on 26th November, 2020.

**Comment by softvision-oana-arbuzov** [comment]
**[Done]** 3rd run - QA Verification progress available here: https://docs.google.com/spreadsheets/d/1F9vcSpLQ_hNBeZinsytGXlfXpJLW6vh7C0BJYtd9hIY/edit?pli=1#gid=1517261890

Interventions to be removed:
https://bugzilla.mozilla.org/show_bug.cgi?id=1679372 Remove Intervention for everyman.co

**Comment by ksy36** [comment]
v.18.1.0 has been shipped https://bugzilla.mozilla.org/show_bug.cgi?id=1663980 and merged to android components repository
