### ISSUE TITLE
2018-Q3 1.2 Diagnose 35 tracking protection “tp-needsrepro” bugs.

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#19]
https://bugzilla.mozilla.org/buglist.cgi?status_whiteboard_type=allwordssubstr&query_format=advanced&status_whiteboard=tp-needsrepro&bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&component=Tracking%20Protection&product=Firefox&list_id=14226328

**Comment by miketaylr** [comment]
Update: Sergiu and Oana have started on this. Have 19 more to go. Many of the older ones no longer reproduce. But lots of traige to do.

On average, we can investigate 5 issues today.

**Comment by miketaylr** [comment]
Status: 2 more issues, one under investigation. one is blocked. Nearly done here.

**Comment by softvision-sergiulogigan** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1410688 - CBS issue (looks like CBS does not support TP)
https://bugzilla.mozilla.org/show_bug.cgi?id=1338483 - Issue being blocked by https://github.com/webcompat/web-bugs/issues/18174

**Comment by miketaylr** [comment]
Update: also working on the "see also" webcompat.com TP issues, ~20 remaining.

**Comment by softvision-sergiulogigan** [comment]
Great success!

We finally finished looking at all the Tracking protection items.

So, for the "2018-Q3 1.2 Diagnose 35 tracking protection “tp-needsrepro” bugs" OKR (https://github.com/mozilla/webcompat-team-okrs/issues/19), we still have 1 more issue that's currently untestable, due to a blocker.
https://github.com/webcompat/web-bugs/issues/18174 blocks https://bugzilla.mozilla.org/show_bug.cgi?id=1338483

Regarding the "See Also" list of https://bugzilla.mozilla.org/show_bug.cgi?id=1101005, we still have 2 more issues. One is related to analytics.google.com where we have no access (but Adam was pinged) and for the other one we are waiting for a confirmation (also from Adam).
We started with 81 issues in that list. Some were not reproducible anymore, but for those who did reproduce, we opened Bugzilla issues and linked them to the appropriate meta bug (tpvideo, tplogin, tpimages, tpcomments, trackingprotection).

The average time needed to fully diagnose one item was about 30 minutes.
