### ISSUE TITLE
2021Q1 - Report Site Issue button in the new Proton UI for Firefox

### ISSUE THREAD

**Issue by karlcow** [mozilla/webcompat-team-okrs#192]
There's a work going on redesigning the UI of Firefox. The meatball menu will disappear. 

Currently "Report Site Issue…" is inside the meatball menu. What should happen to it on DevEdition and Nightly, what would be its new home. 

The argument is that is an essential feature providing valuable feedback to make Firefox Release more usable. If it becomes less visible, webcompat will loose its main agency for getting the webcompat issues. 

Discussions have been started.

**Comment by denschub** [comment]
The current state is a planned experiment to place the reporter into the "Help" menu next to the "Report Deceptive Site..." entry. Tracking bugs:

- https://bugzilla.mozilla.org/show_bug.cgi?id=1690573
- https://jira.mozilla.com/browse/FIDEFE-13

**Comment by denschub** [comment]
The change is landed in Nightly now. The current implementation is not perfect and would need some cleanup, but that's fine since it also means we can revert the change without too much pain. In this Nightly cycle, which has its soft freeze on 2021-03-18, we have to carefully look at the reports to see if we should intervene before this ends up in beta.

I'll volunteer to write a little script that tries to generate some meaningful comparison between the number of reports of this Nightly cycle vs. previous cycles. Given how important the reporter is, and how short a single Nightly cycle is, I'll treat this with high priority.

**Comment by denschub** [comment]
I'll also make sure to add an agenda item to the 2021-03-16 team meeting. At that time, we should have a fairly good understanding of how this impacts us, and it's a great time to make a final decision on this change, with two days to land a backout before soft-freeze.

**Comment by denschub** [comment]
So, [I built a little script to extract the number of reports per day for each version cycle](https://0b101010.codes/mozilla/webcompat-report-cycle-count) on Nightly on Desktop, and unfortunately, our numbers are so low, they're pretty much impossible to interpret in any meaningful way.

Here's a table with reports from Desktop Nightly per day (raw data in CSV form is in the "details" block at the end of the issue):

![Screenshot 2021-03-09 at 00 12 50](https://user-images.githubusercontent.com/344777/110394211-5670fa00-806c-11eb-92c6-7f3d766caef4.png)

So we're not receiving a lot of Desktop Nightly reports, at all. There is no clear trend to see - the 88 numbers aren't particularly high, but also not exceptionally low. And by that, I mean that we're still receiving reports...

Drawing a graph with these numbers is pretty, but absolutely meaningless:

![Screenshot 2021-03-09 at 00 14 43](https://user-images.githubusercontent.com/344777/110394303-7ef8f400-806c-11eb-88f5-426fe6198f73.png)

Looking at the average number of reports per day for the Nightly 79 to 87 cycles, we can see that the number appears to be somewhat "stable":

![Screenshot 2021-03-09 at 00 48 48](https://user-images.githubusercontent.com/344777/110397004-54f60080-8071-11eb-9594-7dcbe0b41785.png)

For 79 to 87, we averaged 1.226 reports/day over the entire 4-week cycle. For the 88 cycle up until now, the average is 1.357 - so technically, the new location is performing *slightly* better. However, as I said, the numbers are so small and so noisy, I'd be very careful with taking that as a signal.

---

For comparison, I also ran the numbers for Beta versions. 

![Screenshot 2021-03-09 at 00 17 33](https://user-images.githubusercontent.com/344777/110394536-e31bb800-806c-11eb-90c0-76e1583e3a63.png)

The data for beta is also **super** noisy, and maybe just as hard to interpret as the Nightly data. However, if we draw a graph:

![Screenshot 2021-03-09 at 00 18 24](https://user-images.githubusercontent.com/344777/110394661-18280a80-806d-11eb-8f82-6945f7ee9a91.png)

It's noticeable that we're seeing a but of a high in the 3rd week of the release cycle, and that we're rarely seeing zero reports in a day. The trend towards the 3rd cycle week becomes more obvious if we're looking at an average over beta 78 to 86:

![Screenshot 2021-03-09 at 00 46 27](https://user-images.githubusercontent.com/344777/110396849-034d7600-8071-11eb-9104-f7df7404fbcf.png)

---

I'm not really sure what to advise based on those numbers. It seems clear that the location change did not result in our numbers dropping to zero - we're still getting reports. But it's hard to say if there's a drop in volume, given the overall volume is so low, it's hard to say anything at all.

So, while I'll run the script again to check Nightly numbers next week, I don't think we can make a good judgement here, just based off these numbers. So we can

- let this change ride to Beta, and see if we notice anything there.
- look at the telemetry numbers for total clicks on the report item - which may be a higher number and includes people who do not actually submit a report.

---

<details>
Data for Nightly cycles:

```csv
Version,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28
79,1,1,0,0,4,2,1,0,1,2,0,0,2,1,2,4,1,2,0,1,1,3,3,1,0,1,0,1,3
80,1,2,1,0,2,0,3,2,1,3,1,0,0,2,2,1,3,1,0,0,1,1,1,2,1,0,0,2,0
81,2,1,1,0,0,0,1,0,0,2,1,0,3,0,0,3,1,1,0,0,0,1,1,1,3,1,0,0,1
82,1,3,0,2,2,0,2,2,1,1,1,0,0,0,2,1,0,1,0,3,5,1,2,1,1,3,0,3,1
83,0,1,0,0,1,1,0,1,5,2,2,1,2,3,0,3,4,2,1,0,2,0,0,1,1,2,0,3,3
84,0,2,1,4,0,0,1,0,1,2,4,1,0,0,2,4,1,1,1,0,2,1,1,2,1,0,1,3,1
85,0,2,1,0,0,0,2,4,2,1,1,1,2,3,3,1,1,2,1,3,0,0,1,1,0,0,1,1,2
86,2,1,0,0,0,1,0,0,0,2,3,0,1,1,1,0,1,0,0,1,1,1,3,2,0,0,2,0,1
87,0,3,1,2,3,3,1,2,1,0,2,0,3,1,0,3,4,0,1,2,2,0,2,1,1,4,4,1,1
88,2,2,3,1,0,1,2,4,0,1,0,1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
```

Data for Beta cycles:

```csv
Version,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28
78,1,5,4,1,7,14,2,9,9,9,9,6,8,6,17,14,14,14,12,0,22,14,8,7,3,0,8,2,4
79,1,5,7,2,6,4,3,8,6,5,9,5,5,12,21,6,20,4,4,12,13,14,9,8,6,5,14,9,12
80,0,3,6,0,5,3,6,7,3,5,7,3,4,10,12,7,16,16,16,16,16,17,19,17,7,8,8,3,5
81,2,4,11,10,14,9,19,22,9,11,13,9,1,8,5,21,15,19,18,14,17,12,24,15,19,4,2,12,4
82,1,8,5,6,7,6,9,15,7,14,6,9,2,4,16,20,24,14,20,9,14,26,20,12,12,8,4,4,8
83,0,5,4,6,3,1,7,6,8,8,1,5,5,8,8,18,19,19,7,12,24,17,20,18,9,2,7,7,11
84,2,0,3,5,4,4,6,2,8,8,12,3,11,13,12,14,21,5,16,12,9,22,16,20,4,10,7,14,0
85,2,2,3,4,7,3,6,5,13,11,3,4,2,8,3,3,11,6,7,8,18,19,16,16,19,17,9,16,17
86,1,6,4,8,3,7,8,8,9,6,8,11,3,4,9,14,14,20,9,8,9,15,13,6,8,12,6,0,2
87,2,4,10,6,8,2,26,14,16,12,10,8,8,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
```
</details>

**Comment by karlcow** [comment]
Fantastic work @denschub 
It would interesting to correlate this with the click on the button. aka how many click on the report site issue vs bug reported. 

In the script I see that you used ` issue.body.includes("<!-- @reported_with: desktop-reporter -->") &&` which is the right thing, but I can't help myself trying to understand why we have so many `unknown` for `@reported_with`.

Example: https://github.com/webcompat/web-bugs/issues/68012

```
<!-- @reported_with: unknown -->
```

if it was reported directly from the website, it should have `<!-- @reported_with: web -->`. Either we have a bug or there is a glitch somewhere. 
https://github.com/webcompat/webcompat.com/blob/07b93ecb3534c06869bd834c384afff321899a3c/webcompat/form.py#L268

Ah I just tried with "Report Site Issue" on nightly.

Sometimes it gets it and sometimes it just doesn't get it and when this happens

```
document.getElementsByClassName('form')[0].elements.reported_with.value
"unknown"
```

oopsie.

**Comment by karlcow** [comment]
Maybe you can try the graph with `unknown` added.

**Comment by denschub** [comment]
Good point!

Numbers with `unknown` added are a bit higher, but overall still very chaotic:

![Screenshot 2021-03-09 at 01 22 57](https://user-images.githubusercontent.com/344777/110399355-026b1300-8076-11eb-9c2d-96f3e51b3f65.png)

![Screenshot 2021-03-09 at 01 23 15](https://user-images.githubusercontent.com/344777/110399371-0bf47b00-8076-11eb-9baf-4e8f8ed9ca3b.png)

Looking at an average of the previous cycles and the current 88 cycle:

![Screenshot 2021-03-09 at 01 24 54](https://user-images.githubusercontent.com/344777/110399530-478f4500-8076-11eb-95d7-b3d2e405e5bc.png)

Including `unknown` reports, 79 to 87 had an average of 1.666 reports/day, the 88 cycle up until now is at 1.714 reports/day. Still looks like 88 is slightly over-performing, albeit well within the error-bars, and nothing I could consider significant.

Will try to get some telemetry numbers for comparison. :)

<details>
CSV sources:

```csv
Version,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28
79,1,1,0,0,4,2,1,0,1,2,0,0,2,1,2,4,1,2,0,1,1,3,3,1,0,1,0,1,3
80,1,2,1,0,2,0,3,2,1,3,1,0,0,2,2,1,3,1,0,0,1,2,1,2,2,1,1,3,0
81,3,2,2,0,0,1,2,0,2,3,1,1,3,1,0,3,1,1,0,1,2,1,2,1,3,1,0,0,1
82,2,4,0,2,2,0,4,3,1,1,1,0,1,0,2,2,0,1,0,3,5,1,2,1,3,3,0,4,1
83,0,2,3,1,3,1,1,1,6,2,3,2,2,3,2,3,6,3,2,1,3,1,0,1,1,2,0,4,3
84,0,2,2,5,1,1,1,1,1,2,6,1,0,0,3,4,3,1,1,0,2,4,1,3,1,2,2,4,1
85,1,2,1,0,0,0,4,4,2,4,1,3,3,3,3,2,2,3,1,3,0,1,1,1,0,1,1,3,2
86,2,3,0,0,1,1,0,0,0,2,3,2,1,1,1,1,2,0,0,2,1,2,3,2,0,2,2,1,2
87,0,3,2,2,3,3,1,5,2,1,2,0,3,4,2,3,5,0,1,2,2,1,6,1,1,4,4,2,1
88,2,2,3,2,1,1,3,5,1,1,0,1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
```
</details>

**Comment by denschub** [comment]
I did a very early analysis for the first couple of days in Beta. From there it looks like we're slightly underperforming:

![Screenshot 2021-03-26 at 20 16 36](https://user-images.githubusercontent.com/344777/112682312-40d34100-8e70-11eb-8525-86aee0e33101.png)

But the good news is that we still receive reports, so it doesn't look like an emergency yet. Will take a second look in one week when I'm back from PTO.

**Comment by denschub** [comment]
I've marked previous graphs as obsolete given they contain outdated data. Also, this time, I spent some time to draw *proper* graphs, including a visualization of the usual noise range and even proper labels! Charts below are also available [as an interactive version](https://stuff.overengineer.dev/mozilla/webcompat/webcompat-okrs-192-report.html) which allows you to watch the graph in your own resolution and hide certain datasets if needed.

Let's start with the noisier dataset...

## Nightly

The reporter's new place has been in Nightly for almost two full cycles now. Here's the result:

![nightly](https://user-images.githubusercontent.com/344777/114767955-92ccff80-9d68-11eb-8259-d720e29db8e7.png)

As you can see, the error bars (i.e. the gray area) in the Nightly data we have are huge.  We frequently see zero reports on a few days for Nightly, and the average is hovering at somewhere about 2 reports. Both 88 and 89 are well within that. The data is really noisy, but I think **the new placement didn't significantly affect Nightly users**.

Now, the more important one...

## Beta

Unfortunately, the story looks a bit different here. We've almost completed the 88 cycle, and there is a noticeable difference:

![beta](https://user-images.githubusercontent.com/344777/114768342-03741c00-9d69-11eb-9d1b-c5ba6dc1196c.png)

While Beta also has large error bars, there's a noticeable trend upwards towards the second half of the cycle. So far, we did not see the same uptick in the 88 cycle at all. In fact, it looks like the 88 cycle is always performing at the lower bound of reports and sometimes outside the range we expect. Drawing conclusions here is a bit difficult. We can say that **we still receive some reports**, which is a good thing. At the same time, **we see significantly less reports from Beta users than we expect**, especially during the ongoing second half of the cycle. Dropping down from ~15 reports a day to ~5 reports if we're lucky is a bit of an issue.

One should note that we were a bit unlucky and uncoordinated with the change. The reporter got moved out of the "meatball menu" before the meatball menu disappeared. So instead of the whole menu disappearing, thus forcing users to discover the new placement, the item just vanished and that might very well leave the impression that we just removed the item. The whole menu is removed with 89 now, so users might go on a discovery tour if they want to report something.

## Next steps?

I see two possible next steps here.

1.) Build a patch that adds the reporter either directly into the menubar, or place the reporter directly into the toolbar. This would probably increase the volume of reports significantly (probably above the levels we've had before).
2.) Remain in the "help" section for another cycle and see if the numbers improve now that the whole meatball menu is gone in 89.

I'm having a hard time picking one option. I'd happily vote for 1 if we received no issues at all, but we still see *some*. Given we have a large backlog and a huge spike in numbers driven by Firefox for iOS, maybe the little downtime is good and we can revisit the issue with 89 is nearing its completion. On the other hand, Firefox Desktop is our most important product, and Desktop Beta users have been a valuable source of reports in the past.

@karlcow @ksy36 @wisniewskit - what do y'all think? Have you felt like there was a noticeable lack in valuable Desktop diagnosis work recently? Do you think we should place ourselves more prominently? Or do you think this new placement is doing fine, given your anecdotal experience and those numbers? :)

**Comment by wisniewskit** [comment]
If a cycle just means a month (plus the extra 2 weeks of this cycle) then I'm not against waiting, because the major changes might inspire folks to look for the option again if that hypothesis is true.

But I can't be sure if it's not better for us to try to experiment with placement instead if we have the bandwidth. That is, some A/B tests if that's viable (given that it's only on beta and nightly).

Before we take any steps it may also be worth cross-referencing to see whether there's a difference in the number of users testing on nightly/beta during this cycle, as that might help explain things as well.

**Comment by ksy36** [comment]
Thanks for putting together the report! I would probably vote for option 2 at this point given the influx of iOS issues. But I personally think it's worth experimenting with option 1 in the meantime (so at least we could have some ideas/approvals for the next cycle).

Wonder if you had a chance to look at google analytics as it's showing statistics on how many users land on the form page? It's probably a fair metric that we should take into account. We're measuring reports, but it's rather a tricky task given that very little percent of visits results in a report. And it's not something we can control really. But it's safe to assume the more visits we get, the more reports we receive (not necessarily valid though :) ).

**Comment by ksy36** [comment]
For page visits I compared two periods:
Mar 21, 2021 - Apr 14, 2021 (most recent) and  Jan 21, 2021 - Feb 15, 2021 (before the change):

![Screen Shot 2021-04-14 at 6 18 16 PM](https://user-images.githubusercontent.com/1303908/114787437-d108f580-9d4d-11eb-9ae5-54b2dd12c853.png)

So we can assume the change affect page visits in Windows the most (-73.99%) and then Mac (-54.84%).

Also we can check goal completion (when the form is submitted) in column "Submit issue (Goal 1 Completions)".
Windows users submitted 45 reports in the recent period as opposed to 167 in the period before the change (-73.05% loss). It kind of similar to page visits drop, however there is not necessarily a direct correlation

**Comment by denschub** [comment]
Thanks for sharing those numbers. I'm somehow good at ignoring that we have those... A ~70% drop in traffic correlates with the number of reports in the second half (15/day vs 5/day), so it's good to see those numbers match.

**Comment by karlcow** [comment]
@denschub Thanks for the awesome work on this. This is impressive.
@ksy36 Thanks also to bring another data set. Wonderful. 
Really proud of the team


Are the menus less accessible on windows than on macOS. aka is it more confusing to access.
 on macOS, there are two ways to access:
1. The top bar menu in the finder
2. The 3 bar menu on the top right of the window. (somehow I keep forgetting about this one)

I wonder if report site issue should be in the contextual menu too which is used a lot by devs. 

The 70% drop for windows users is worrying. But I also wonder if it matches Easter season and holidays, where windows machines are mostly used in… work environments. A bit like spam is low on week-ends, because work computers are switched off. 

@ksy36 in the stats per day for windows users is there enough data to show a drop during holiday season or is it mostly flat?

Also weird that there is exactly the same number of submitted issues on Android (21), Linux, Macintosh (5)

 Also why the source is desktop-reporter for Android. 

Sorry for the many questions.

**Comment by karlcow** [comment]
As for the options, I would be inclined to go with option 2 because of the current flood of firefox ios issues.

**Comment by denschub** [comment]
Okay, seems we have consensus here. I'll spend some "a bit lower priority" time this cycle to gauge if we can build some experimentation around that, but for now, I'll communicate that we're fine with the help menu for 89 at least. Appreciate the feedback. <3

**Comment by denschub** [comment]
I did re-run the numbers!

## Beta 89

For beta 89 now that we're almost at the end. I updated the [interactive version](https://stuff.overengineer.dev/mozilla/webcompat/webcompat-okrs-192-report.html), but here's a screenshot:

![Screen Shot 2021-05-19 at 20 32 43](https://user-images.githubusercontent.com/344777/118865657-754c0200-b8e1-11eb-9ce0-c58fb23c2d07.png)

And it looks like the numbers for beta have increased a bit, so more people are re-discovering the entry. The mean has increased to 5.58 reports/day on beta, which is good.

## Nightly 90

Interestingly, the 90 **Nightly** cycle was one of our strongest cycles, ever, setting quite a few report records:

![Screen Shot 2021-05-19 at 20 35 56](https://user-images.githubusercontent.com/344777/118866043-e4295b00-b8e1-11eb-8d2d-e8485e39ff87.png)

The mean for the 90 Nightly cycle is 6.34 reports/day. So it somehow outperformed 89 Beta, and pretty much all previous Nightly cycles. I don't know why that is, but I think that's good.

**Comment by denschub** [comment]
I ran the data one last time.

* Interactive chart: https://stuff.overengineer.dev/mozilla/webcompat/webcompat-okrs-192-report.html
* Code and data: https://0b101010.codes/mozilla/webcompat-report-cycle-count

The numbers are still not as high as they were before, but they have stabilized at a level we're fine with right now. Given the uptake in iOS reports, the little bit lower report rate from desktop is probably even a feature. We still see desktop issues, and the reports we've been getting are quite valuable, so this is good.

In the future, we can run experiments around maybe enabling the reporter in Release versions as well, but that's work for a future time. As H1 is nearing its end, I'll close this issue and mark it as a success. :)

**Comment by karlcow** [comment]
@denschub Thanks for doing this work. This was useful to help us decide if the button was at the right place or not. I wonder if a blog post could be interesting, explaining the work done here and sharing the code with the larger community.

**Comment by RokeJulianLockhart** [comment]
It's not there anymore. I've been unable to locate it.

**Comment by denschub** [comment]
@RokeJulianLockhart please check out [this reply I just posted to Mozilla Connect](https://connect.mozilla.org/t5/ideas/add-a-button-to-report-websites-that-are-not-compatible-with/idc-p/43099#M24928) for an update on the reporter! :)
