### ISSUE TITLE
2018-Q4 1.1 - Ship Blipz v2 SHIELD experiment

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#27]
Ship the second iteration to experiment with scaling up crowdsourcing funnel by prompting users.

* [x] Get UX signoff
* [x] Finish UI implementation
* [x] Get data + legal signoff
* [x] Get QA signoff
* [x] Get Firefox Peer signoff
* [x] Ship it
* [ ] Document findings

**Comment by miketaylr** [comment]
Update: ready for QA and Peer signoff.

**Comment by wisniewskit** [comment]
Update: the first (big) round of QA is done, and I will be posting the addon for review early this week unless there is some unexpected major change necessary.

**Comment by wisniewskit** [comment]
We're finally done with QA and the addon is reviewed. Now waiting on signing and deployment, which may end up happening next Monday.

**Comment by wisniewskit** [comment]
We shipped yesterday, so with luck we'll have some data to look at by the time the All Hands swings around.

**Comment by wisniewskit** [comment]
We're done with the coding now, as far as I can tell. Version 2.1's launch is imminent, and it addresses the final tweaks to our reporting/labels/UI that are worth doing in this iteration. That leaves us with the documentation of the findings, and since it will take two weeks for the experiment to run, it'll be close to the end of the quarter before we can do that part.

**Comment by miketaylr** [comment]
In theory the study ended yesterday (there's always a few stragglers due to the nature of sending updates to users). We're triaging the final bugs and telemetry data this week, will have next steps / go-no-go details by early next week. Still On Track.

**Comment by miketaylr** [comment]
Mike to link final report
