### ISSUE TITLE
2019-Q1 3.2 - Add 3 dashboards to track "needscontact", "sitewait", "needstriage" bug states to webcompatmetrics

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#48]
The final output should be the functional dashboards for the following bugs milestones, that live @ http://webcompat-dashboard.herokuapp.com:
* [x] needstriage
* [x] needscontact
* [x] sitewait

Tasks:

* [x] database work + refactoring
* [x] server side gathering of milestones data
* [x] front-end refactoring
* [x] front-end implementation

**Comment by magsout** [comment]
👍 /claim

**Comment by magsout** [comment]
- [ ] front-end refactoring

**Comment by laghee** [comment]
Update: getting back up to speed on what's todo and where to start with database re-tool. Will check in with @karlcow when he's back on his feet.

**Comment by karlcow** [comment]
Make progress on this today. 
Added a scheduler with a script to fetch the data count for any milestones. Next step will be to actually store them in a DB so we can get rid of our hackish server data request on @karlcow and @laghee servers.

**Comment by laghee** [comment]
Discussion on how to shape the database is in progress. https://github.com/webcompat/webcompat-metrics-server/issues/67

**Comment by karlcow** [comment]
@laghee finished her script. We need to plug a DB. We have the schema, we just need to dive in…

**Comment by karlcow** [comment]
So we are approaching the end. @laghee is doing a **major work there**. 

* DB is working
* We started to gather the data for two sets

Next steps:
* test by plugging a route to the DB
* then if it's working, importing the old data in the DB
* and plug the old routes to the DB.

**Comment by laghee** [comment]
@karlcow merged my test route, so that is now set up. The endpoint does a database query and returns needsdiagnosis data according to selected params and works from the server side (e.g., https://webcompat-metrics.herokuapp.com/data/needsdiagnosis-dbtest?from=2019-02-26&to=2019-03-11)

But something in the configuration isn't quite right (possibly either an integer vs. string or param-handling issue), and it's making the client side unhappy. I've pinged @magsout for [help in figuring out what specifically is going wrong](https://github.com/webcompat/webcompat-metrics-client/issues/145#issuecomment-471513578). As soon as we get that sorted, we're ready to port existing data, change over the old routes, and add the new dashboards.

**Comment by laghee** [comment]
Basic DB query endpoint now works with client side requests.

Since we're down to 10 days on this and the OKR as stated doesn't actually merging the old data from `needsdiagnosis` and `weeklyreports`, I'm thinking I'll address the data migration and updates to existing routes after I add in the structure for the three new dashboards. That way we can count this as done as soon as those are working, and the DB loose ends can be tied up into the start of Q2. 

### Remaining tasks:
**Server-side**:
- [ ] set up scripts for `needstriage`, `needscontact`, `sitewait`
- [ ] add routes for new dashboards
_...and then_
- [ ] update old server routes to query DB
- [ ] importing existing data to DB

**Client-side**:
- [ ] add new metrics containers for `needstriage`, `needscontact`, `sitewait`

**Comment by laghee** [comment]
I was delayed a bit wrangling (high-maintenance 😜) visiting family members, but I'm going to power through the remaining tasks here in the next couple of days.

**Comment by miketaylr** [comment]
Awesome!

**Comment by laghee** [comment]
OK, depending on how we / @miketaylr / the powers that be want to judge things... we could possibly call this done (at least superficially): 
![Screenshot 2019-03-29 21 04 57](https://user-images.githubusercontent.com/20972610/55259573-56ec9d80-5266-11e9-8e2c-534dbe7660ac.png)
The database exists and is slowly filling up with counts (older data still to be ported in). The framework for DB-query-based routes is in place, but not yet 100% live.

**However**... all three dashboards _are_ live and accumulating more data by the hour.

**Comment by miketaylr** [comment]
This is so cooooooool @laghee. Thank you and @magsout and @karlcow.
